-- Drop and create MAISON_DB
DROP DATABASE IF EXISTS MAISON_DB;
CREATE DATABASE MAISON_DB;

-- Temporarily disable foreign key checks to prevent dependency errors during creation
SET FOREIGN_KEY_CHECKS = 0;

SET sql_mode = '';

-- Use MAISON_DB for the following operations
USE MAISON_DB;

-- ==== Cities == Table Creation ====

CREATE TABLE `Cities`
(
    zipcode   INT PRIMARY KEY,
    place     VARCHAR(127),
    province  VARCHAR(127),
    latitude  INT NOT NULL, -- stored as ×10000, invisible to backend
    longitude INT NOT NULL, -- stored as ×10000, invisible to backend
    UNIQUE KEY place_province (place, province)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- ==== Users == Table Creation ====

CREATE TABLE `Users`
(
    user_id         BIGINT PRIMARY KEY,                  -- generated by backend (uu_id to long)
    user_first_name VARCHAR(128),                        -- Some users may not have a first name
    user_last_name  VARCHAR(128),                        -- Some users may not have a last name
    user_name       VARCHAR(255) UNIQUE NOT NULL,        -- must be unique
    email           VARCHAR(255) UNIQUE NOT NULL,        -- must be unique, for login (always lowercase)
    avatar_url      VARCHAR(255),                        -- _url to the avatar image, null if not set
    password_hash   VARCHAR(255)        NOT NULL,        -- hashed password
    gender          BOOLEAN,                             -- 0 for male, 1 for female, null if not set
    birth_date      DATE,                                -- null if not set
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- account creation time
    login_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login_time TIMESTAMP           NULL             -- last login time
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- ==== Categories == Table Creation ====

CREATE TABLE `Categories`
(
    cat_id INT AUTO_INCREMENT PRIMARY KEY, -- cat_id auto-incremented, always > 0
    name   VARCHAR(64) UNIQUE NOT NULL     -- Category name, must be unique
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

-- ==== Provider-related Tables == Table Creation ====

-- Provider_certificates table
CREATE TABLE `Provider_certificates`
(
    certificate_id BIGINT AUTO_INCREMENT PRIMARY KEY, -- certificate_id auto-incremented, always > 0
    file_url       VARCHAR(255)                       -- _url to the certificate file
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;


-- Provider_applications table
CREATE TABLE `Provider_applications`
(
    application_id BIGINT AUTO_INCREMENT PRIMARY KEY,                          -- application_id auto-incremented, always > 0
    user_id        BIGINT NOT NULL,                                            -- Foreign key to `Users` table
    cat_id         INT    NOT NULL,                                            -- Foreign key to `Categories` table
    description    TEXT,                                                       -- Application description
    city_zipcode   INT    NOT NULL,                                            -- foreign key to Cities table, optional, can be null
    status         ENUM ('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING', -- Application status
    FOREIGN KEY (user_id) REFERENCES `Users` (user_id),
    FOREIGN KEY (cat_id) REFERENCES `Categories` (cat_id),
    FOREIGN KEY (city_zipcode) REFERENCES Cities (zipcode)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

-- Provider_certificates associated with Provider_applications
CREATE TABLE `Provider_application_certificates`
(
    application_id BIGINT NOT NULL, -- Foreign key to `Provider_applications` table
    certificate_id BIGINT NOT NULL, -- Foreign key to `Provider_certificates` table
    PRIMARY KEY (application_id, certificate_id),
    FOREIGN KEY (application_id) REFERENCES `Provider_applications` (application_id),
    FOREIGN KEY (certificate_id) REFERENCES `Provider_certificates` (certificate_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- Provider_labels table
CREATE TABLE `Provider_labels`
(
    label_id BIGINT AUTO_INCREMENT PRIMARY KEY, -- label_id auto-incremented, always > 0
    name     VARCHAR(64) UNIQUE NOT NULL        -- Label name, must be unique
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

-- Provider_infos: table to check if user is a provider
CREATE TABLE `Provider_infos`
(
    provider_id     BIGINT PRIMARY KEY,                  -- Foreign key to `Users` table
    cat_id          INT UNIQUE NOT NULL,                 -- Foreign key to `Categories` table
    description     TEXT,                                -- Application description
    service_offered TEXT,                                -- Detailed services as a JSON string
    city_zipcode    INT        NOT NULL,                 -- foreign key to Cities table, optional, can be null
    service_area    TEXT,                                -- Service area as a descriptive text
    price_range     VARCHAR(64),                         -- Price range as a string
    authorized_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Time when the provider was authorized
    FOREIGN KEY (provider_id) REFERENCES `Users` (user_id),
    FOREIGN KEY (cat_id) REFERENCES `Categories` (cat_id),
    FOREIGN KEY (city_zipcode) REFERENCES Cities (zipcode)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

-- Provider_labels associated with Provider_infos
CREATE TABLE `Provider_info_labels`
(
    provider_id BIGINT NOT NULL,        -- Foreign key to `Provider_infos` table
    label_id    BIGINT NOT NULL UNIQUE, -- Foreign key to `Provider_labels` table
    PRIMARY KEY (provider_id, label_id),
    FOREIGN KEY (provider_id) REFERENCES `Provider_infos` (provider_id),
    FOREIGN KEY (label_id) REFERENCES `Provider_labels` (label_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;


-- ==== Task and Order Tables == Table Creation ====

-- Tasks table
CREATE TABLE `Tasks`
(
    task_id          BIGINT PRIMARY KEY,                                                                -- generated by backend (uu_id to long)
    customer_id      BIGINT       NOT NULL,                                                             -- Foreign key to `Users` table
    title            VARCHAR(128) NOT NULL,                                                             -- Task title
    cat_id           INT          NOT NULL,                                                             -- Foreign key to `Categories` table
    frequency        ENUM ('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY')             DEFAULT 'ONCE',            -- Task frequency
    city_zipcode     INT          NOT NULL,                                                             -- foreign key to Cities table
    start_time       TIMESTAMP    NOT NULL,                                                             -- Task start time
    end_time         TIMESTAMP    NOT NULL,                                                             -- Task end time
    address          VARCHAR(255) NOT NULL,                                                             -- Task address
    budget           INT          NOT NULL,                                                             -- Task budget in cents
    customer_contact TEXT         NOT NULL,                                                             -- Customer contact information
    description      TEXT         NOT NULL,                                                             -- Task description
    status           ENUM ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED') DEFAULT 'PENDING',
    created_at       TIMESTAMP                                               DEFAULT CURRENT_TIMESTAMP, -- Task creation time
    FOREIGN KEY (customer_id) REFERENCES `Users` (user_id),
    FOREIGN KEY (cat_id) REFERENCES `Categories` (cat_id),
    FOREIGN KEY (city_zipcode) REFERENCES `Cities` (zipcode)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- Order table
CREATE TABLE `Orders`
(
    order_id     BIGINT PRIMARY KEY,                  -- Foreign key to `Tasks` table
    provider_id  BIGINT NOT NULL,                     -- Foreign key to `Provider_infos` table, ensures the provider is authorized
    confirmed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Order confirmation time
    FOREIGN KEY (order_id) REFERENCES `Tasks` (task_id),
    FOREIGN KEY (provider_id) REFERENCES `Provider_infos` (provider_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- Review table
CREATE TABLE `Reviews`
(
    order_id    BIGINT PRIMARY KEY, -- Foreign key to `Orders` table, ensures the review is linked to an order
    ranking     INT,
    review_text TEXT,
    FOREIGN KEY (order_id) REFERENCES `Orders` (order_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- ==== Chat Tables == Table Creation ====

-- Conversation table
CREATE TABLE `Conversations`
(
    chat_id  BIGINT PRIMARY KEY AUTO_INCREMENT, -- chat_id auto-incremented, always > 0
    user1_id BIGINT,
    user2_id BIGINT,
    FOREIGN KEY (user1_id) REFERENCES `Users` (user_id),
    FOREIGN KEY (user2_id) REFERENCES `Users` (user_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

CREATE TABLE `Chat_messages`
(
    message_id    BIGINT PRIMARY KEY AUTO_INCREMENT,   -- message_id auto-incremented, always > 0
    chat_id       BIGINT  NOT NULL,                    -- Foreign key to `Conversations` table
    sent_by_user1 BOOLEAN NOT NULL,                    -- true if sent by user1, false if sent by user2
    content       TEXT    NOT NULL,                    -- Message content
    sent_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Message sent time
    FOREIGN KEY (chat_id) REFERENCES `Conversations` (chat_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

CREATE TABLE `Notice_messages`
(
    notice_id BIGINT AUTO_INCREMENT PRIMARY KEY,                      -- notice_id auto-incremented, always > 0
    user_id   BIGINT,                                                 -- Receiver, null for system-w_ide notices
    title     VARCHAR(64) NOT NULL,                                   -- Notice title
    content   TEXT        NOT NULL,                                   -- Message content
    type      ENUM ('NOTICE', 'SYSTEM', 'WARNING')  DEFAULT 'NOTICE', -- Notice type
    sent_time TIMESTAMP                             DEFAULT CURRENT_TIMESTAMP,
    targets   ENUM ('ALL', 'PROVIDERS', 'PERSONAL') DEFAULT 'ALL'     -- Target audience
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  AUTO_INCREMENT = 1;

-- ==== Multilingual Support Tables == Table Creation ====

CREATE TABLE `Multilingual_tags`
(
    id       BIGINT PRIMARY KEY AUTO_INCREMENT,
    tag      VARCHAR(128)                                                    NOT NULL,
    language ENUM ('ENGLISH', 'CHINESE_MANDARIN', 'JOSEONJOK_MAL', 'FRENCH') NOT NULL,
    content  TEXT                                                            NOT NULL,
    UNIQUE (tag, language)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE `Admins`
(
    admin_id      BIGINT PRIMARY KEY,           -- generated by backend (uu_id to long)
    admin_name    VARCHAR(255) UNIQUE NOT NULL, -- must be unique
    password_hash VARCHAR(255)        NOT NULL  -- hashed password
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- Restore foreign key checks
SET FOREIGN_KEY_CHECKS = 1;